Feature/jp 15 map
JourneyPlanner/JourneyPlanner pull request #104
Opened 2024-05-13 06:08 UTC by EinSev

2024-05-13 07:13 UTC, Ixpiria reviewed
When entering a random address that does not exist, the map takes a random address in the world.

2024-05-13 07:17 UTC, Mathematti commented
> When entering a random address that does not exist, the map takes a random address in the world.

no it doesn't, it uses the one which is the most similar to what you entered

2024-05-13 14:48 UTC, stefll requested changes
Design Review: An sich ist Design mäßig alles in Ordnung außer eben dass ich nciht nachschauen kann ob der pin richtig ist

2024-05-13 14:48 UTC, stefll commented on backend/app/Http/Controllers/ActivityController.php
>          if (array_key_exists("date", $validated) && $validated["date"]) {
- kann nicht checken wie die Pinfarbe ist wenn die aktivität im kalender ist -> Fehler wird angezeigt

2024-05-13 14:48 UTC, stefll commented on backend/app/Http/Controllers/ActivityController.php
>          if (array_key_exists("date", $validated) && $validated["date"]) {
+ eben die schon erwähnten fehler wie dass die adresse bei der aktivitäten beim bearbeiten nicht mehr angezeigt wird

2024-05-14 13:23 UTC, Mathematti commented
Deployment check ✅

2024-05-15 09:33 UTC, Ixpiria reviewed
When changing the Address of an Activity and then clicking on that Activity again there is nothing displayed in the Address Field

2024-05-15 15:39 UTC, stefll requested changes
Design Review: 2 Sachen

2024-05-15 15:39 UTC, stefll commented on backend/app/Http/Controllers/JourneyController.php
> +            array_key_exists("mapbox_full_address", $validated) &&
Bei so Reisen wo das Reiziel ein Ziel ist dass Mapbox nicht kennt/nicht exestiert (z.B. Testlandia) werden auch die Adressen der Aktivitäten nicht auf der Map angezeigt und gelten als "nicht gefunden"

2024-05-15 15:39 UTC, stefll commented on backend/app/Http/Controllers/JourneyController.php
> +            $geocodingResponse = Http::get(
Die Pins kriegen auch nicht die richtige Farbe

2024-05-16 16:14 UTC, stefll requested changes
Design Review: To add -> Tabelle

2024-05-16 16:14 UTC, stefll commented on backend/app/Http/Controllers/JourneyController.php
> +            $geocodingData = $geocodingResponse->json();
Eigentlich sollte hierfür das Icon angezeigt werden dass keine Adresse gefunden wurde (also dieses Warning sign)
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/bea45fe2-06aa-48c4-bf4b-d9eebfda2e9d)

2024-05-16 16:14 UTC, stefll commented on backend/app/Http/Controllers/JourneyController.php
> +                $journey->longitude =
Die Tabelle hat jetzt ein Update bekommen auf Figma -> nach bauen wenn es geht

2024-05-16 16:23 UTC, Ixpiria approved these changes, later dismissed

2024-05-16 16:47 UTC, Mathematti commented on backend/app/Http/Controllers/JourneyController.php
> +                $journey->longitude =
Ich finde es genial, dass die Tabelle jetzt im Backen ist :D

2024-05-16 19:39 UTC, stefll requested changes
Design Review: Dialog

2024-05-16 19:39 UTC, stefll commented on frontend/components/ActivityMap.vue
> +            class="relative mt-5 flex h-96 w-[90%] items-end sm:w-5/6 md:ml-[10%] md:w-[calc(50%+16rem)] md:justify-start lg:ml-10 lg:w-[calc(33.33vw+38.5rem)] xl:ml-[10%] xl:w-[calc(33.33vw+44rem)]"
Kannst die Map in der Handy Version kleiner machen? Also die Höhe? Die neue Höhe sollte zumindest die hälfte von der höhe der jetzigen Karte

2024-05-16 19:39 UTC, stefll commented on frontend/components/ActivityMap.vue
> +            <Dialog
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/8162d8c5-9b11-45f2-a44a-da11ade33e43)
Für das Pop up (beim Laptop, Handy passt)
-> Die Schrift größe bei der Tabelle zumindest eine Schriftgröße größer
-> die linke seite der Tabelle näher an die rechte (nicht in der mitte teilen -> zu viel white space)
-> größe des Pop ups so dass 5 inputs OHNE zu scrollen sichtbar sind
-> Abstand ist zwischen den Infos (Aktivitäten Name, angegebene Adresse) zu groß -> kleiner machen
-> "Wir konnten diese Aktivität ....." -Text weiter nach oben rücken (auch für die Handy Version bitte)

2024-05-18 22:26 UTC, stefll reviewed
Design Review: Everything looks fine

2024-05-18 22:27 UTC, stefll approved these changes, later dismissed

2024-05-19 09:57 UTC, stefll approved these changes
Design Review: Looks good

2024-05-19 12:45 UTC, Ixpiria approved these changes

2024-05-19 13:01 UTC, merged