Feature/jp 23 imprint
JourneyPlanner/JourneyPlanner pull request #105
Opened 2024-05-13 16:53 UTC by EinSev

2024-05-14 06:41 UTC, Mathematti commented on frontend/pages/imprint.vue
> please report this to the e-mail address below

The email address is above

2024-05-14 06:41 UTC, Mathematti commented on frontend/pages/imprint.vue
and also here
>  please let us know via the contact e-mail address below

2024-05-14 06:41 UTC, Mathematti commented on frontend/pages/imprint.vue
Do we need a "Blattlinie"? We aren't a news company

2024-05-14 06:41 UTC, Mathematti commented on frontend/pages/imprint.vue
Do we want to give credit to the icons here once again?

2024-05-16 06:16 UTC, Mathematti commented on frontend/pages/imprint.vue
Maybe add an empty line here in between
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/77683178/5d4724ad-2925-4d93-ba27-f5a3d876ea03)

2024-05-16 06:22 UTC, Mathematti commented on frontend/pages/imprint.vue
> +                    </a>
This link leads absolutely nowhere

2024-05-16 06:26 UTC, Mathematti requested changes

2024-05-16 06:26 UTC, Mathematti commented on frontend/pages/imprint.vue
> +                    >
This link leads to http://localhost:3000/www.ris.bka.gv.at%E2%80%8C%E2%80%8C%E2%80%8C%E2%80%8C%E2%80%8C%E2%80%8C%E2%80%8D%E2%80%8C%E2%80%8C

2024-05-16 17:03 UTC, Mathematti requested changes

2024-05-16 17:03 UTC, Mathematti commented on frontend/pages/imprint.vue
> +                        >http://ec.europa.eu/odr
why no safe link? why not https://ec.europa.eu/odr

2024-05-16 17:03 UTC, Mathematti commented on frontend/pages/imprint.vue
> +                    </a>
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/77683178/2116c0bd-7679-4318-8ab6-ab3eb406d41b)

2024-05-16 17:03 UTC, Mathematti commented on frontend/pages/imprint.vue
> +                        <T key-name="www.ris.bka.gv.at" />
This still leads to localhost, I think you need to add the protocol

2024-05-16 18:34 UTC, stefll requested changes
Design-Review: Paar Abstände hinzugefügt und entfernt

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p class="mt-4">
noch ein mb-2

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +            <div class="mx-5 mt-10 flex flex-col sm:mx-20 lg:mx-52 xl:mx-96">
mt-10 zu mt-7

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                class="mr-10 mt-5 rounded-xl border-2 border-cta-border bg-input px-2 py-1 text-base font-semibold hover:bg-cta-bg dark:bg-input-dark dark:text-input dark:hover:bg-cta-bg-dark"
px-2 zu px-6

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p>
mt-1

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p>
mt-1

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p>
mt-1

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                    </a>
^

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p>
mt-1

2024-05-16 18:34 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p>
mt-1

2024-05-18 22:40 UTC, stefll requested changes
Design Review: Almost Done

2024-05-18 22:40 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p class="mt-1">
zu dem mt-1 beim p-tag das mb-2

2024-05-18 22:40 UTC, stefll commented on frontend/pages/imprint.vue
> +                <p>
bitte bei dem p-tag eine mt-1 machen

2024-05-19 09:31 UTC, Mathematti approved these changes

2024-05-19 10:00 UTC, stefll approved these changes
Design Review: Everything looks fine

2024-05-19 10:00 UTC, merged