Feature/jp 99 figma color chaos
JourneyPlanner/JourneyPlanner pull request #113
Opened 2024-05-26 17:45 UTC by Ixpiria

2024-06-04 08:10 UTC, EinSev requested changes

2024-06-04 08:10 UTC, EinSev commented on frontend/app.vue
> +                class="dark:text-input flex h-screen flex-col items-center justify-center gap-5 text-text"
text-input?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +            "text-error dark:text-error-dark hover:underline font-bold",
text error colors

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto h-9 w-40 rounded-xl border-2 border-mahagony-400 bg-natural-50 px-2 font-bold text-text hover:bg-mahagony-300 dark:text-natural-50 dark:hove
backgorund-dark

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto flex h-9 w-40 flex-row justify-center rounded-xl border-2 border-dandelion-300 bg-natural-50 text-center text-text hover:bg-dandelion-200 da
backgorund

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto h-9 w-40 rounded-xl border-2 border-mahagony-400 bg-natural-50 px-2 font-bold text-text hover:bg-mahagony-300 dark:text-natural-50 dark:hove
backgorund

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto h-9 w-40 rounded-xl border-2 border-dandelion-300 bg-natural-50 px-2 font-bold text-text hover:bg-dandelion-200 dark:text-natural-50 dark:ho
backgorund

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto h-9 w-40 rounded-xl border-2 border-mahagony-400 bg-natural-50 px-2 font-bold text-text hover:bg-mahagony-300 dark:text-natural-50 dark:hove
backgorund

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto flex h-9 w-40 flex-row justify-center rounded-xl border-2 border-atlantis-400 bg-natural-50 text-center text-text hover:bg-atlantis-200 dark
backgorund

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityMap.vue
> +                class="pi pi-exclamation-circle text-cancel-border -mb-2.5 ml-auto text-xl hover:cursor-pointer"
name correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityMap.vue
> +                            class="dark:text-input flex flex-col font-nunito text-text"
name correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityMap.vue
> +                    class="border-border-gray dark:border-input-placeholder border-b-2 pb-3"
names correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityMap.vue
> +                        class="dark:text-input mx-4 font-nunito text-text lg:mx-8"
name correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/ActivityMap.vue
> +                                class="dark:border-input border-b border-text text-xs uppercase"
name correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/CalendarFull.vue
> +    text = fullConfig.theme.accentColor["natural-50"] as string;
nice, since when does that work?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/CalendarFull.vue
> +    border = "#50A1C0";
can we do that here too?

2024-06-04 08:10 UTC, EinSev commented on frontend/components/form/Calendar.vue
> +                    class: 'text-text dark:text-input flex gap-1 font-nunito',
text-input correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/imprint.vue
> +                class="dark:hover:bg-cta-bg-dark mr-2 mt-5 rounded-xl border-2 border-dandelion-300 bg-natural-50 px-2 py-1 text-base font-semibold hover:bg-dandelion-200 dark:bg-pesto-600 dark:text-
bg-cta-bg-dark?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +    lightColor = fullConfig.theme.accentColor["card-dark"] as string;
these two correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                class="border-calypso-300-grey dark:border-text-disabled flex items-center border-b-2 pb-4"
border-text-disabled?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                class="dark:bg-calypso-300-dark invisible w-0 rounded-3xl border-solid bg-background dark:bg-dark max-md:h-0 md:visible md:h-64 md:w-64 lg:h-72 lg:w-72"
bg-calypso-300-**dark**?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                    class="text-surface border md:hidden md:w-0"
surface correct?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                    class: 'bg-input dark:bg-input-dark text-text dark:text-natural-50 font-nunito',
input und input-dark?

2024-06-04 08:10 UTC, EinSev commented on frontend/pages/login.vue
> +                    class="focus:ring-indigo-500 focus:border-indigo-500 dark:bg-surface-dark flex h-auto w-full flex-col items-center rounded-3xl border-2 border-calypso-300 bg-calypso-200 bg-opacit
surface? and double bg?

2024-06-04 08:10 UTC, EinSev commented on frontend/tailwind.config.js
> +            light: "#F6FAFB",
why do we need these

2024-06-04 08:30 UTC, EinSev commented
and build fails + resolve conflicts

2024-06-04 13:37 UTC, Ixpiria commented on frontend/components/ActivityDialog.vue
> +                    class="dark:bg-backgorund-dark mt-auto h-9 w-40 rounded-xl border-2 border-mahagony-400 bg-natural-50 px-2 font-bold text-text hover:bg-mahagony-300 dark:text-natural-50 dark:hove
gibts noch

2024-06-04 14:29 UTC, Ixpiria commented on frontend/components/CalendarFull.vue
> +    border = "#50A1C0";
no

2024-06-04 14:55 UTC, Ixpiria commented on frontend/tailwind.config.js
> +            light: "#F6FAFB",
we need

2024-07-27 22:09 UTC, Mathematti commented on docker/tusd/tusd_windows_amd64/tusd.exe
Please delete this and all the other tus related files

2024-07-29 19:42 UTC, EinSev requested changes

2024-07-29 19:42 UTC, EinSev commented on frontend/app.vue
>              :height="3"
double, prob merge error

2024-07-29 19:42 UTC, EinSev commented on frontend/app.vue
> +    @apply min-h-screen bg-background font-nunito dark:bg-background-dark;
also double

2024-07-29 19:42 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +            }
double code here too

2024-07-29 19:42 UTC, EinSev commented on frontend/components/ActivityMap.vue
Zeilen 20-32: wurden die Farben gecheckt @Ixpiria @stefll ?

2024-07-29 19:42 UTC, EinSev commented on frontend/components/ActivityMap.vue
Zeile 132: class vom Dialog, die Farben gibts nicht mehr
Edit: bzw generell die pass through sachen von dem Dialog haben noch alte Farben

2024-07-29 19:42 UTC, EinSev commented on frontend/components/ActivityMap.vue
> +                        barX: 'h-1.5 bg-natural-300 hover:bg-border-light dark:bg-[#888] dark:hover:bg-[#555]',
border-light gibts nicht mehr oder

2024-07-29 19:42 UTC, EinSev commented on frontend/components/form/AddressInput.vue
> +const bg = "";
const wegen ESLINT? aber irgendwie wird die variable zwar weiter unten geused aber sie bekommt nie einen wert, idk wo da was schief gelaufen ist und ob sie notwendig ist

2024-07-29 19:42 UTC, EinSev commented on frontend/components/form/AddressInput.vue
>      hoverCancel = fullConfig.theme.accentColor["cancel-bg-dark"] as string;
cance-bg-dark gibts nich mehr oder

2024-07-29 19:42 UTC, EinSev commented on frontend/components/form/Calendar.vue
> +                    class: 'text-text dark:text-bg-natural-50 flex gap-1 font-nunito',
text-bg-natural-50? das bg ist prob falsch da nehm ich an

2024-07-29 19:42 UTC, EinSev commented on frontend/components/form/Checkbox.vue
> +            class="text-gray-900 dark:text-gray-300 ms-2 select-none font-nunito text-sm font-light dark:text-natural-50"
gibt kein gray im tailwind file

2024-07-29 19:42 UTC, EinSev commented on frontend/components/form/Checkbox.vue
> +            class="dark:text-mahaogony-300 ml-9 text-left text-xs text-mahagony-600 dark:font-bold"
typo

2024-07-29 19:42 UTC, EinSev commented on frontend/components/svg/copy.vue
ich nehm an width/height ist schon durch nen merge wieder dazugekommen und wurde nicht aktiv geändert, wird wohl so passen dann

2024-07-29 19:42 UTC, EinSev commented on frontend/components/svg/search-icon.vue
zeile 17: dark:fill-text-text und dark:stroke-text-text glaube nochmal anschauen

2024-07-29 19:42 UTC, EinSev commented on frontend/pages/journey/[id].vue
zeile 103-4: white, card-dark gibt es nicht

2024-07-29 19:42 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                                    class="dark:bg-calypso-300-dark -mr-1 h-fit w-full rounded-b-2xl border-x-2 border-b-2 border-natural-200 bg-natural-50 text-sm dark:border-gothic-600 dark:bg-dark
dark:bg-calypso-300-dark nochmal anschauen

2024-07-29 19:42 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                                    class="dark:bg-calypso-300-dark flex h-full w-full justify-center rounded-b-2xl border-x-2 border-b-2 border-natural-200 bg-natural-50 text-sm dark:border-gothic-6
same thing here too calypso-300-dark gibts wohl nicht

2024-09-02 15:13 UTC, EinSev requested changes

2024-09-02 15:13 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +                                    class="dark flex h-full w-full justify-center rounded-b-2xl border-x-2 border-b-2 border-natural-200 bg-natural-50 text-sm dark:border-gothic-600 dark:bg-dark"
dark am Anfang unnötig?

2024-09-02 15:13 UTC, EinSev commented on docker/tusd/tusd.ps1
sollten das skript und das ignore file nicht bleiben @Mathematti ?

2024-09-02 15:21 UTC, EinSev requested changes

2024-09-02 15:21 UTC, EinSev commented on frontend/components/MediaGallery.vue
>                              class: 'display-block flex-none font-bold font-nunito',
aus zufall rauf gestoßen, irgendwas ist scuffed mit dem button

![image](https://github.com/user-attachments/assets/63df13a5-11b7-4b90-a59f-fa4720490db7)

2024-09-02 15:24 UTC, Mathematti commented on docker/tusd/tusd.ps1
sollten sie

2024-09-04 05:53 UTC, EinSev approved these changes

2024-09-04 05:57 UTC, stefll approved these changes
Design Review: Okay

2024-09-04 05:57 UTC, stefll commented on frontend/pages/dashboard.vue
> +            class="mt-5 flex items-center justify-between border-b-2 border-calypso-400 pb-3 md:pb-5"
Die Farbe ist falsch. Es sollte calypso-300 sein

2024-09-04 05:57 UTC, stefll commented on frontend/components/DashboardItem.vue
>          label: t.value("dashboard.options.header"),
Ich weiß nicht wo es zu finden ist aber kann bitte das "menü" der einzelnen Reisen (also wenn man auf die drei Punkte klickt) 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/ce747235-a170-42b8-a28a-03a9b5735673)
, die Farben so umändern wie bei dem Sorting-menü
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/a49f6a4a-89d8-407c-82f7-1ffd6c955c79)

2024-09-04 06:00 UTC, merged