fix: handle invite and journey not found better
JourneyPlanner/JourneyPlanner pull request #134
Opened 2024-06-15 15:42 UTC by EinSev

Didn't do much design for the error page because its a DA goal.

2024-06-16 18:40 UTC, Ixpiria submitted a review, later dismissed

2024-06-17 11:07 UTC, stefll requested changes
Design Review: Paar sachen fehlen

2024-06-17 11:07 UTC, stefll commented on frontend/error.vue
> +            <a class="text-xs" href="mailto:contact@journeyplanner.io"
Dieser Mail to link so stylen wie bei dem footer + noch eine underline

2024-06-17 11:07 UTC, stefll commented on frontend/error.vue
> +                <button class="m-3 rounded-lg border p-1" @click="handleError">
Den button stylen wie alle anderen buttons (gelben border, wei0er bg, beim hovern -> gelben bg)

2024-06-17 11:07 UTC, stefll commented on frontend/error.vue
> +            </p>
Dark Mode nicht vergessen

2024-06-18 08:18 UTC, stefll approved these changes

2024-06-18 08:50 UTC, Ixpiria approved these changes

2024-06-18 08:50 UTC, merged