feature/JP-6-login
JourneyPlanner/JourneyPlanner pull request #16
Opened 2024-03-11 21:44 UTC by Ixpiria

2024-03-11 22:01 UTC, EinSev requested changes

2024-03-11 22:01 UTC, EinSev commented on frontend/components/svg/cloudReversed.vue
Please rename to "cloud-reversed.vue"

2024-03-11 22:01 UTC, EinSev commented on frontend/pages/login.vue
> + * @param {Object} userData
@param Object? I think its User

2024-03-11 22:01 UTC, EinSev commented on frontend/pages/login.vue
> +  loginUser(values);
Please fix TypeScript error:

```
Argument of type 'GenericObject' is not assignable to parameter of type 'User'.
  Type 'GenericObject' is missing the following properties from type 'User': email, passwordts-plugin(2345)
(parameter) values: GenericObject
```

2024-03-11 22:01 UTC, EinSev commented on frontend/pages/login.vue
> +        <SvgBalloon
Something went wrong exporting these svgs, they have the wrong color.

2024-03-11 22:01 UTC, EinSev commented on frontend/pages/login.vue
> +import { useTranslate, T, useTolgee } from "@tolgee/vue";
Remove unused import

2024-03-11 22:44 UTC, EinSev submitted a review, later dismissed

2024-03-12 07:30 UTC, stefll approved these changes
Design Review: Okay
Habt ihr super gemacht

2024-03-12 07:31 UTC, EinSev approved these changes

2024-03-12 07:32 UTC, merged