feat: Improved registration with first and last name
JourneyPlanner/JourneyPlanner pull request #20
Opened 2024-03-13 05:54 UTC by Mathematti

2024-03-13 05:58 UTC, Mathematti commented
@Ixpiria is there any particular reason why the browser doesn't suggest an email anymore? I think it's an improvement that it actually saves the correct fields but it would be even better if both of these could be done

2024-03-13 06:16 UTC, Ixpiria commented
> @Ixpiria is there any particular reason why the browser doesn't suggest an email anymore? I think it's an improvement that it actually saves the correct fields but it would be even better if both of these could be done

Idk warum das sein sollte ich habe nur 2 Input fields geadded das sollte das ja nicht beeinflussen

2024-03-13 06:18 UTC, Mathematti commented
> > @Ixpiria is there any particular reason why the browser doesn't suggest an email anymore? I think it's an improvement that it actually saves the correct fields but it would be even better if both of these could be done
> 
> Idk warum das sein sollte ich habe nur 2 Input fields geadded das sollte das ja nicht beeinflussen

I think it's due to the username field not existing anymore which causes the browser to use the email field

2024-03-13 06:21 UTC, EinSev commented
There is an autocomplete tag in HTML
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2024-03-15 17:13 UTC, EinSev submitted a review, later dismissed
Looks good, maybe we find a solution for email autocomplete some day

2024-03-15 17:13 UTC, EinSev commented on frontend/pages/register.vue
> +  console.log(values);
Please remove console.log

2024-03-16 12:30 UTC, EinSev submitted a review, later dismissed

2024-03-18 19:22 UTC, stefll requested changes
Design Review: Also alles in einem passt nur 2 Sachen angemerkt

2024-03-18 19:22 UTC, stefll commented on frontend/pages/register.vue
> +              <FormPassword
ich weiß ich hab es vorher nicht angesprochen aber wäre es möglich den Fehler Text mit dem normalen Text zu alignen
?
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/16a7c234-31f8-44d4-bdd3-f14e3e2f1ef5)

2024-03-18 19:22 UTC, stefll commented on frontend/pages/register.vue
> +            <FormInput
So wie es jetzt ist mit dem Vor und Nachname ist auch gut.
ABER WENN du lust hast ODER denkst dass es machbar ist kannst du PROBIEREN eher so einen Layout zu gestalten
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/22115de5-d090-4bb1-8f3b-c06e4dd48d1f)
Es würde nur für die desktop version sein also am handy bleibt es gleich wie jetzt.
ABER WIRKLICH NUR WENN DU ZEIT UND LUST HAST ES ZU PROBIEREN. WENN ES NICHT FUNKTIONIERT LASS ES EINFACH!!! ES PASST SO AUCH!!!

2024-03-18 19:22 UTC, stefll commented on frontend/pages/register.vue
> +              id="lastName"
Ich weiß nicht aber vielleicht sollte man neben Nachname auch so ein in klammern ein "(optional)" hin machen, damit der User weiß, dass er nicht seinen Nachnamen eintippen muss.

2024-03-22 19:57 UTC, Ixpiria commented on frontend/pages/register.vue
> +            <FormInput
Habs probiert ist aber leider schwierig mit der Fehlermedlung

2024-03-26 19:56 UTC, EinSev reviewed
Code okay

2024-03-26 21:32 UTC, stefll requested changes
Design review: Ja sonst passt alles aber das mit dem footer muss gefixt werden

2024-03-26 21:32 UTC, stefll commented on frontend/pages/register.vue
>            </NuxtLink>
Ich weiß nicht genau wo das hier im code zu finden ist aber dieses Problem soll bitte gefixt werden. Wenn du es nicht siehst mach dein Fenster kleiner
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/bb2ab809-c6dc-4bd2-8794-c086724bb341)

2024-03-28 11:15 UTC, Mathematti commented
please merge main branch and resolve conflicts

2024-03-29 23:23 UTC, EinSev approved these changes, later dismissed

2024-03-30 20:30 UTC, stefll requested changes
Design Review: Nur eine winzige Kleinigkeit

2024-03-30 20:30 UTC, stefll commented on frontend/pages/register.vue
> +                  translationKey="form.input.password.repeat" />
ich weiß ihr hasst mich alle aber kann man das Datenschutz ding noch etwas nach oben geben

2024-03-30 23:46 UTC, EinSev approved these changes, later dismissed

2024-03-31 00:05 UTC, EinSev commented
I don't know what happened after #[242641f](https://github.com/JourneyPlanner/JourneyPlanner/pull/20/commits/242641f65ad77ffdc62565c272233f4bfcb5bd8a), but build error is now fixed

2024-03-31 00:06 UTC, EinSev approved these changes

2024-03-31 19:58 UTC, stefll approved these changes
Design Review: Everything looks fine

2024-03-31 19:58 UTC, merged