feature/JP-64-page-transitions
JourneyPlanner/JourneyPlanner pull request #21
Opened 2024-03-14 22:31 UTC by EinSev

2024-03-15 07:17 UTC, Mathematti commented on frontend/pages/journey/new.vue
> +  //middleware: ["sanctum:auth"],
TODO

2024-03-15 07:17 UTC, Mathematti commented on frontend/layouts/default.vue
> +</template>
Missing empty line at the end of the file

2024-03-15 12:17 UTC, Ixpiria approved these changes

2024-03-18 19:27 UTC, stefll requested changes
Design Review: All good

2024-03-18 19:32 UTC, stefll approved these changes
Design Review: All Good

2024-03-28 10:46 UTC, merged