JP-180: feat: now dateCounter should work properly
JourneyPlanner/JourneyPlanner pull request #248
Opened 2024-09-02 15:36 UTC by Ixpiria

2024-09-02 15:56 UTC, stefll requested changes
Date counter does not work

2024-09-02 15:56 UTC, stefll commented on frontend/pages/journey/[id].vue
>  import resolveConfig from "tailwindcss/resolveConfig";
date counter does not work properly 
![image](https://github.com/user-attachments/assets/d339b833-c04a-4a5d-a708-5f12cd41be3f)

2024-09-04 17:58 UTC, EinSev requested changes

2024-09-04 17:58 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +console.log(days.value);
please remove console.log

2024-09-04 20:10 UTC, EinSev approved these changes

2024-09-16 19:04 UTC, stefll approved these changes
Design Review: Looks good

2024-09-16 19:04 UTC, merged