Feature/jp 81 user settings
JourneyPlanner/JourneyPlanner pull request #279
Opened 2024-09-21 09:59 UTC by Ixpiria

2024-09-21 16:29 UTC, EinSev requested changes
generelle sachen:
- focus-ring color
- die neuen Files in Form "Dialog" noch hinten dran pls und extra settings Folder geben
- texte nochmal überprüfen so wie ich mal gesagt hab

2024-09-21 16:29 UTC, EinSev commented on backend/app/Http/Controllers/UserController.php
Password check could be made a separate function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +const colorScheme = ref("test");
test?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +const isDisplaynameChangeVisible = ref(false);
for better clarity Dialog keyword could be added
e.g. `isEmailChangeDialogVisible`

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +const usernameInvalid = ref(false);
for better clarity is keyword could be used (`isUsernameInvalid`)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +const emit = defineEmits(["close"]);
for better clarity emit should be near the top of the file, e.g. under the props

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +const colorMode = useColorMode();
could also be moved up to the other const definitons

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +function handleChange() {
for better clarity a more clear name like` changeColorMode` should be used

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +function handleChange() {
Please add a comment describing the function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +async function changeUsername(newUsername: string) {
Please add a comment describing the function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +async function changeDisplayname(newDisplayname: string) {
Please add a comment describing the function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +const { data: currUser } = await useAsyncData("userRole", () =>
`userRole` might not be the best identifier for this request

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +async function changeEmail(newEmail: Ref) {
Please add a comment describing the function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
We have a the vee-validate libarary for validating forms, is there are reason why you decided to use if-checks instead?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +<template>
Content of template have a single route element, like a `<div>`


[Nuxt documentation](https://nuxt.com/docs/guide/directory-structure/pages)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                class: 'z-30 self-center text-natural-500 hover:text-text dark:text-natural-400 dark:hover:text-text h-10 w-10 ',
dark hover color shouldn't be the same as light hover color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +        <div class="pl-4 pt-4 dark:text-natural-50">
please also set the text color for lightmode

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                <div class="bg h-0.5 w-10 bg-calypso-400" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-5 text-3xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                        class="rounded-md border-2 border-natural-400 bg-natural-100 pl-3 text-text placeholder:text-text hover:border-calypso-400 hover:bg-natural-50 dark:border-natural-700 dark:bg-
is it intended by design to set the current displayname as placeholder? @stefll 
if yes, should the placeholder text color be the same as the input text color?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                        detail: t.value("username.changed.toast.success"),
username key shouldn't be used for display name

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-5 text-3xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                        class="overflow-hidden overflow-ellipsis dark:text-natural-300"
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-5 text-3xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-5 text-3xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +    await logout();
maybe a toast message would explain the short waiting time for the user?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                class: 'flex justify-start pb-2 pl-9 font-nunito bg-background dark:bg-background-dark dark:text-natural-50',
also set the lightmode text-color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                @click="$emit('close')"
call your close() function to keep it consistent

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +        <div class="pl-4 dark:text-natural-50">
Please also set lightmode text color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-2 text-2xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <button
I think that should be centered, for all the buttons

![image](https://github.com/user-attachments/assets/6fc4f20b-c5f6-4824-a33e-12c8b61c9f9c)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +    <Sidebar
The buttons should have the same length

![image](https://github.com/user-attachments/assets/8ea927f8-8403-401e-bee9-72588625aa8f)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-2 text-2xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    class="flex-grow-5 dark:text-white mx-2 text-2xl font-semibold text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

you already set the text color out the top div, I think you don't need it here anymore

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +    <Sidebar
For all descriptions you don't set lightmode text-color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +async function deleteAccount() {
Please add comment describing the function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +<template>
Content of template have a single route element, like a `<div>`

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                <div class="bg h-0.5 w-5 bg-mahagony-500" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                <div class="bg h-0.5 flex-grow bg-mahagony-500" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                <b class="dark:text-natural-50">
also set lightmode text color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                    @click="$emit('close')"
call your close() function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                @click="$emit('close')"
call close function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                <b class="dark:text-natural-50">
also set light mode color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +            <div
Abstand nach fettem Teil

![image](https://github.com/user-attachments/assets/5b527950-a937-4d1f-92be-a811ac690018)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                        class="mb-3 mr-10 w-full rounded-md border-2 border-natural-400 bg-natural-100 py-1 pl-3 text-text placeholder:text-text hover:border-calypso-400 dark:border-natural-700 dark:
da stimmt was bei den farben nicht, bzw focus-ring

![image](https://github.com/user-attachments/assets/0503ef5b-0954-4a8f-9ee4-f94affb2eca5)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                        @click="$emit('close')"
call close function

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                        class="w-40 rounded-md bg-natural-50 px-2 text-2xl hover:underline dark:bg-background-dark dark:text-natural-50"
also set lightmode color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +    <Sidebar
description missing?

![image](https://github.com/user-attachments/assets/fc1de266-e7d7-4182-87ef-89b370e10bb7)

bzw sieht man nur wenn sehr klein

![image](https://github.com/user-attachments/assets/0eeac844-1269-46af-a0aa-9dd637c715eb)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                <b class="dark:text-natural-50">
also set lightmode text-color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +                        class="w-40 rounded-md bg-natural-50 px-2 text-2xl hover:underline dark:bg-background-dark dark:text-natural-50"
also set lightmode text-color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
> +function changeUsername() {
changeUsername?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
> +        :header="t('dashboard.user.settings')"
remove wrong header

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
> +        :header="t('dashboard.user.settings')"
remove wrong header

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
> +                @click="$emit('close')"
call close()

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
> +                        class="mb-2 mr-10 flex w-full items-start text-sm dark:text-natural-50"
light text-color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
> +                        id="username"
displayname

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
> +                        class="mr-10 w-full rounded-md border-2 border-natural-400 bg-natural-100 py-1 pl-3 text-text placeholder:text-text hover:border-calypso-400 dark:border-natural-700 dark:bg-na
check focus-ring color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +async function changeEmail() {
comment

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +<template>
Content of template must have a single route element, like a `<div>`

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +        :header="t('dashboard.user.settings')"
remove wrong header

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                    class="flex-grow-5 dark:text-white mx-3 text-3xl text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                <div class="bg h-0.5 w-5 bg-calypso-400" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg?

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                    <div class="flex w-2/3 items-start dark:text-natural-50">
lightmode text-color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                    <div class="flex w-2/3 items-start dark:text-natural-50">
lightmode color

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +        :header="t('dashboard.user.settings')"
remove

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                @click="$emit('close')"
close()

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                        class="mb-2 mr-10 flex w-full items-start text-sm dark:text-natural-50"
lightmode text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +                        class="mb-2 mr-10 flex w-full items-start text-sm dark:text-natural-50"
lightmode text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +async function changePassword() {
comment

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +<template>
outer `<div>`

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
![image](https://github.com/user-attachments/assets/e7851260-1bc7-493c-82cb-e3f93bead030)

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                    class="flex-grow-5 dark:text-white mx-5 text-3xl text-text dark:text-natural-50"
white is not a valid color and you are setting dark text-color two times

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                <div class="bg h-0.5 w-10 bg-calypso-400" />
bg

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                <div class="flex w-3/5 justify-start dark:text-natural-50">
lightmode text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                <div class="flex w-3/5 justify-start dark:text-natural-50">
lightmode text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +        :header="t('dashboard.user.settings')"
remove

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                @click="$emit('close')"
close()

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                        class="mb-2 mr-10 flex w-full items-start text-sm dark:text-natural-50"
light text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                        class="mb-2 mr-10 flex w-full items-start text-sm dark:text-natural-50"
light text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
> +                        class="mb-2 mr-10 mt-3 flex w-full items-start text-sm dark:text-natural-50"
light text

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
> +function changeUsername() {
comment

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
> +    <Sidebar
outer `<div>`

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
> +        :header="t('dashboard.user.settings')"
remove

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
> +                @click="$emit('close')"
close

2024-09-21 16:29 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
> +                        class="mb-2 mr-10 flex w-full items-start text-sm dark:text-natural-50"
light text

2024-09-21 16:55 UTC, Ixpiria commented on frontend/components/UserSettings.vue
> +                    <div class="dark:text-natural-300">
this is a different color?

2024-09-21 22:30 UTC, Mathematti commented on backend/app/Http/Controllers/UserController.php
I don't think that makes sense because it's literally just an if statement and inside I return a response. What part of that should be a function in your opinion? Just the part in the if statement?

2024-09-21 22:35 UTC, EinSev commented on backend/app/Http/Controllers/UserController.php
Mhhh yea true

2024-09-22 14:48 UTC, EinSev requested changes
- console logs entfernen
- **die neuen Files in Form "Dialog" noch hinten dran pls und extra settings Folder geben**
- username in Bild richtig anzeigen (MediaGallery.vue setName())

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 w-10 bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                            class="overflow-hidden overflow-ellipsis text-sm dark:text-natural-300"
text-text

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 w-10 bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 w-10 bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +            :header="t('dashboard.user.settings')"
needed?

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 w-6 bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 flex-grow bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 w-6 bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
> +                    <div class="bg h-0.5 w-6 bg-calypso-400" />
bg

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
![image](https://github.com/user-attachments/assets/40989a5d-9c49-4823-9190-a31c295578e8)

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
also use vee-validate for username and displayname?

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
vee-validate?

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
vee-validate?

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
passwort dialog öffnen nachdem man bereits einmal das passwort geändert hat:
![image](https://github.com/user-attachments/assets/fcb309ba-33fd-4e3a-85a6-256b7db5e070)

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/EmailChange.vue
> +    if (newEmail.value == "" || password.value == "") {
you are using vee-validate now, there are yup validation rules

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
vee-validate?

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
keine hover farbe im darkmode bei den dropdowns

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
focus ring color bei displayname und username

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/DisplaynameChange.vue
"placeholder" ist nicht der gleiche Wert wie der name der drüber steht wenn man den Namen vorher im Desktop Mode geändert hat

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/UsernameChange.vue
"placeholder" ist nicht der gleiche Wert wie der name der drüber steht wenn man den Namen vorher im Desktop Mode geändert hat

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/PasswordChange.vue
passwort feld ist gefüllt wenn man geschlossen hat und wieder aufgemacht hat

2024-09-22 14:48 UTC, EinSev commented on frontend/components/form/DeleteAccount.vue
passwort feld ist gefüllt wenn man geschlossen hat und wieder aufgemacht hat

2024-09-22 14:48 UTC, EinSev commented on frontend/components/UserSettings.vue
nach delete kann man sich nicht wieder anmelden da XSRF Token mismatch, ig alle cookies/daten löschen?

2024-09-22 15:53 UTC, stefll requested changes
Design Review is NOT completely done yet (Phone Version review: missing)
Things to change:
- change the error message for dark mode to mahogany-300!!
- focus colour on all inputs should be like in the mockup (calypso-400)
- popups (change email, change password, delete) all have the wrong close-button hover colour in dark mode

2024-09-22 15:53 UTC, stefll commented on frontend/components/UserSettings.vue
> +                            id="username"
Input field should be centered with the Text 
![image](https://github.com/user-attachments/assets/c5ffbe8a-5807-4592-959a-5b9bdf894c6f)

2024-09-22 15:53 UTC, stefll commented on frontend/components/UserSettings.vue
> +                            name="displayname"
Username, Displayname should not be placeholders please

2024-09-22 15:53 UTC, stefll commented on frontend/components/UserSettings.vue
> +                            name="username"
![image](https://github.com/user-attachments/assets/dc0ae3f3-421e-4fb7-976d-efb7806f9c6a)
Error message unnecessary. Please remove it

2024-09-22 15:53 UTC, stefll commented on frontend/components/UserSettings.vue
> +                                key-name="dashboard.user.settings.user.email.description"
Please make the email the current user email semibold 
![image](https://github.com/user-attachments/assets/9c51e8f5-ed3b-4451-b1de-e7f37908b99d)

2024-09-22 15:53 UTC, stefll commented on frontend/components/UserSettings.vue
> +                            id="username"
here u can see its not in the middle 
![image](https://github.com/user-attachments/assets/b4b11ed0-0eb7-4558-8880-4e03e2c163e3)

2024-09-22 15:53 UTC, stefll commented on frontend/components/UserSettings.vue
> +                        <Dropdown
Make the arrows the same color as the text please 
![image](https://github.com/user-attachments/assets/a29c669a-52e0-4dcd-81ab-21a1f275d4e2)

2024-09-22 15:53 UTC, stefll commented on frontend/components/form/EmailChange.vue
> +                >
![image](https://github.com/user-attachments/assets/36708e16-dbdd-45ef-8574-68d78d1798a0)
Please make the current email semibold

2024-09-22 15:53 UTC, stefll commented on frontend/components/form/EmailChange.vue
> +                </div>
![image](https://github.com/user-attachments/assets/ca784666-a442-4c76-a17e-6f5d42184b39)
can u center the input fields and the buttons to the center (blue line shows the centre of the popup)

2024-09-22 15:53 UTC, stefll commented on frontend/components/form/EmailChange.vue
> +                    class: 'font-nunito bg-background dark:bg-background-dark px-0 sm:pl-5 sm:pr-12 h-full',
After closing the Popup the information provided in the input should be reset.

2024-09-22 15:53 UTC, stefll commented on frontend/components/form/PasswordChange.vue
> +const client = useSanctumClient();
After closing the Popup the information provided in the input should be reset.

2024-09-22 15:53 UTC, stefll commented on frontend/components/form/PasswordChange.vue
> +                </div>
Please center the button to the input fields 
![image](https://github.com/user-attachments/assets/80b675c8-13bb-4489-8b8d-3cb495e81a46)

2024-09-22 15:53 UTC, stefll commented on frontend/components/form/DeleteAccount.vue
> +        body: {
I can delete my account without entering my password!!!!! Please fix that

2024-09-22 21:30 UTC, stefll requested changes
Design review still not done yet

2024-09-22 21:30 UTC, stefll commented on frontend/components/settings/DeleteAccount.vue
> +                            id="passwordDeleteMobile"
why is the id here "passwordDelteMobile"?

2024-09-22 21:30 UTC, stefll commented on frontend/components/UserSettings.vue
> +        </Dialog>
![image](https://github.com/user-attachments/assets/d46dd30c-1a50-425e-a101-6f91da744c80)
fix this arrow please

2024-09-22 21:35 UTC, stefll commented on frontend/components/UserSettings.vue
> +                            name="username"
Please look at it again

2024-09-23 18:58 UTC, stefll requested changes
Design Review: Done, still a few things to change
Note: Error-Messages are german in the english version. Please fix

2024-09-23 18:58 UTC, stefll commented on frontend/components/settings/UsernameChange.vue
> +                        key-name="dashboard.user.settings.change.username.description"
![image](https://github.com/user-attachments/assets/358a68cc-2188-4086-9799-8803a9aaa155)
Please break this text into 3 parts

2024-09-23 18:58 UTC, stefll commented on frontend/components/settings/EmailChange.vue
> +                    <T key-name="dashboard.user.settings.email.change" />
![image](https://github.com/user-attachments/assets/73291899-923e-489e-a307-c1c9975eede4)
Make it not split. The text should not break

2024-09-23 18:58 UTC, stefll commented on frontend/components/settings/PasswordChange.vue
> +                    <T key-name="dashboard.user.settings.password.change" />
![image](https://github.com/user-attachments/assets/f498aaf7-d829-4d03-b4d7-fe395e1e925e)
Text shouldn't break

2024-09-23 18:58 UTC, stefll commented on frontend/components/settings/DeleteAccount.vue
> +                            class="flex w-3/5 justify-start text-sm text-mahagony-600 dark:text-mahagony-300"
![image](https://github.com/user-attachments/assets/5e6a27ef-27c7-4f03-9afb-96bff798ae61)
Error text should allign with the start of the input

2024-09-23 18:58 UTC, stefll commented on frontend/components/settings/DeleteAccount.vue
> +                            >{{ errors.password }}</span
Error message should be in english please 
![image](https://github.com/user-attachments/assets/04f87542-bf65-4f5f-8a45-7be23bf9a93a)

2024-09-23 20:51 UTC, EinSev requested changes

2024-09-23 20:51 UTC, EinSev commented on frontend/components/UserSettings.vue
readd check if username is same as old username, then don't show error message

2024-09-23 20:51 UTC, EinSev commented on frontend/components/UserSettings.vue
focus ring colors

2024-09-23 20:51 UTC, EinSev commented on frontend/components/UserSettings.vue
different height of input field in change email and change password @stefll ?

2024-09-23 20:51 UTC, EinSev commented on frontend/components/settings/UsernameChange.vue
Can't change username on mobile

![image](https://github.com/user-attachments/assets/3ce76e86-afbb-4080-865f-de79025eef06)

2024-09-23 20:51 UTC, EinSev commented on frontend/components/settings/EmailChange.vue
~~Cant change email on mobile~~, nvm, please add toast if email has already been taken

2024-09-23 21:34 UTC, stefll requested changes
Design Review: Some things left

2024-09-23 21:34 UTC, stefll commented on frontend/components/UserSettings.vue
> +                    </div>
![image](https://github.com/user-attachments/assets/441f1be3-1478-46fc-ac27-9e5eb3982b92)
can u allign the dropdown menu with the buttons

2024-09-23 21:34 UTC, stefll commented on frontend/components/settings/UsernameChange.vue
> +                            id="username"
![image](https://github.com/user-attachments/assets/6ac2c635-66bc-4cbf-a07c-48ab62cae5dc)
can u put the username into the input field too, please

2024-09-23 21:34 UTC, stefll commented on frontend/components/settings/UsernameChange.vue
> +                            id="username"
Found out Username and Displayname dissapears out of input field after opening it for the second time. Please fix

2024-09-23 21:48 UTC, EinSev submitted a review, later dismissed

2024-09-24 15:13 UTC, EinSev submitted a review, later dismissed

2024-09-24 16:00 UTC, EinSev approved these changes

2024-09-24 19:01 UTC, stefll approved these changes
Design Review: Everything looks good now

2024-09-24 19:03 UTC, merged