Feature/jp 33 weather
JourneyPlanner/JourneyPlanner pull request #286
Opened 2024-09-24 20:48 UTC by Ixpiria

2024-09-24 21:39 UTC, stefll requested changes
Design: Looks good but still some minor things to change

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                        <SvgOtherStripes
Can u make this line shorter please 
![image](https://github.com/user-attachments/assets/8fdb260c-426b-46bf-91d9-2a0499b5a782)

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                            <div class="z-0 ml-6 h-full w-1/2">
Remove the stripes (mobile version)
![image](https://github.com/user-attachments/assets/8e653369-e78c-4df0-9a55-23cdc0f83d34)

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                                        class="-mt-2 ml-8 w-24"
please make this button a little bit smaller and move it to the right more (mobile version: front side and back side please)
![image](https://github.com/user-attachments/assets/e283cdcb-1a45-4060-a4c7-72e283c066f4)

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                                    />
The separators should be a bit longer and please align the the temperature 
![image](https://github.com/user-attachments/assets/6d6ba00f-038d-4405-8494-07d7fce23c35)

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                                    />
You probably have to make the overcast icon slightly bigger. Bc we have the same problem here with another triü 
![image](https://github.com/user-attachments/assets/028882cb-b341-4bf6-9c62-3ec3b40234ef)

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                                            class="mt-1 flex h-full w-full items-center justify-start text-5xl text-text dark:text-natural-50"
![image](https://github.com/user-attachments/assets/d1ec845a-04df-4619-ab7a-2f9d098725fd)
can u move the description more to the middle so its under the temperature, please

2024-09-24 21:39 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                                    />
Or maybe another way (so u dont have to change the size of the icon for each icon)
![image](https://github.com/user-attachments/assets/04328eb6-2ff0-43d6-9283-8a995b5da4c7)

2024-09-24 21:41 UTC, stefll commented on frontend/pages/journey/[id].vue
> +                                            <div class="z-0 ml-6 h-full w-1/2">
![image](https://github.com/user-attachments/assets/137c6c96-8b0d-4f8d-9123-75b8c7056b8b)
So it looks like this
Also check the color of the line. its not the right color

2024-09-24 21:42 UTC, EinSev requested changes

2024-09-24 21:42 UTC, EinSev commented on frontend/components/SmallWeather.vue
> +    qrCode: { type: String, required: true },
not needed

2024-09-24 21:42 UTC, EinSev commented on frontend/components/WeatherIcon.vue
Dark mode icons are not used

2024-09-24 21:42 UTC, EinSev commented on frontend/pages/journey/[id].vue
> +import SmallWeather from "~/components/SmallWeather.vue";
import needed? Nuxt should auto import

2024-09-24 22:02 UTC, EinSev approved these changes, later dismissed

2024-09-25 08:52 UTC, EinSev approved these changes

2024-09-25 08:53 UTC, stefll approved these changes
Design Review: Looks good good

2024-09-25 09:01 UTC, merged