JP-182: now we should not be illegal anymore
JourneyPlanner/JourneyPlanner pull request #355
Opened 2024-11-06 21:18 UTC by Ixpiria

2024-11-06 23:18 UTC, EinSev requested changes

2024-11-06 23:18 UTC, EinSev commented on frontend/components/journey/id/TicketSection.vue
please create a new component in journey/id/dialogs for the license dialog

2024-11-06 23:18 UTC, EinSev commented on frontend/components/journey/id/TicketSection.vue
i think the link should be real link and the attribution should also link to the attribution license

https://open-meteo.com/
https://creativecommons.org/licenses/by/4.0/

2024-11-06 23:18 UTC, EinSev commented on frontend/components/journey/id/TicketSection.vue
idk if we should fix this @Mathematti 

![image](https://github.com/user-attachments/assets/e191ad9d-ae00-464f-8c68-23799d9371d8)

2024-11-06 23:18 UTC, EinSev commented on frontend/components/journey/id/TicketSection.vue
neuer bug gefunden: wetter refreshed nicht wenn ich reiseziel bearbeite

kannst vlt die refresh() methode davon verwenden, verwende das auch grad für show templates
https://nuxt.com/docs/api/composables/use-fetch

2024-11-06 23:18 UTC, EinSev commented on frontend/components/journey/id/TicketSection.vue
reminder: den User nicht Siezen (d.h. nicht den text vom translator copy pasten ohne nachzuschauen :p habs schon angepasst)

2024-11-06 23:18 UTC, EinSev commented on frontend/components/journey/id/TicketSection.vue
> +                                        <div class="pl-[1px]">i</div>
pi-info-circle

2024-11-06 23:23 UTC, EinSev requested changes
vlt sollte das Backend trotzdem auch angepasst werden damit was sinnvolles zurückkommt wenn die location nicht passt? @Mathematti 

    "message": "Trying to access array offset on value of type null",

2024-11-07 14:49 UTC, stefll requested changes
Design Review: Hab jetzt den Margin bissi gefixt. Ich mach noch ein geneaueres design für den Link und ein anderes icon für Darkmode

2024-11-07 20:40 UTC, EinSev requested changes

2024-11-07 20:40 UTC, EinSev commented on frontend/components/journey/id/dialogs/LicenseDialog.vue
pls links in neuem tab öffnen lassen und nuxt link usen
https://nuxt.com/docs/api/components/nuxt-link#external-routing

2024-11-07 20:40 UTC, EinSev commented on frontend/components/svg/weather/weather-not-found-dark.vue
mir ist wieder aufgefallen das wir ja sogar alles immer doppelt also light und dark component haben, vlt können wir das in dem branch auch minimieren auf nur einen komponenten pro svg? weil der style ist sogar in den svgs nach unten ausgelagert, dh man müsste nur die klassen namen vereinheitlichen und die styles richtig copy pasten und .dark bzw .light

2024-11-07 20:40 UTC, EinSev commented on frontend/components/journey/id/dialogs/LicenseDialog.vue
absicht das der strich im header h-1 statt wie sonst meistens h-0.5 ist? @stefll

2024-11-12 21:37 UTC, EinSev approved these changes, later dismissed
Code review okay, bis auf den einen requested Change halt noch aber das ist ne style frage

2024-11-15 13:46 UTC, stefll approved these changes, later dismissed
Design Review: Looks good

2024-11-15 20:44 UTC, stefll submitted a review, later dismissed
Design Review: Now everythig should be okay

2024-11-16 07:58 UTC, Ixpiria commented on frontend/components/journey/id/dialogs/LicenseDialog.vue
> +                },
already has aria label

2024-11-16 08:27 UTC, Ixpiria commented on frontend/components/journey/id/TicketSection.vue
> +}
already checked before calling the function

2024-11-16 18:22 UTC, EinSev approved these changes

2024-11-16 18:23 UTC, stefll approved these changes

2024-11-16 18:23 UTC, merged