feat: JP-92 oauth
JourneyPlanner/JourneyPlanner pull request #356
Opened 2024-11-07 10:51 UTC by EinSev

![image](https://github.com/user-attachments/assets/55858cb7-bfeb-4732-abbb-ebe1fe3e7012)

dark mode wäre möglich:
google button würde dann halt so ausschauen
![image](https://github.com/user-attachments/assets/dc439a69-4807-4194-88bb-a6527dff233d)

und microsoft so
https://learn.microsoft.com/en-us/entra/identity-platform/media/howto-add-branding-in-apps/ms-symbollockup_signin_dark.svg

2024-11-14 12:16 UTC, stefll requested changes
Design: Pushed some changes, idk how to fix this issue tho

2024-11-14 12:16 UTC, stefll commented on frontend/components/form/OAuth.vue
> +    <div class="flex w-full items-center">
![image](https://github.com/user-attachments/assets/127b5676-7609-4b55-a10e-9d943fe7bc84)
diese Linie soll weiter herrausragen ohne dass es die Linie bei Registrieren beeinflusst

2024-11-15 13:34 UTC, stefll approved these changes, later dismissed
Design Review: Everything looks good

2024-11-15 13:40 UTC, stefll approved these changes
Design: Looks good

2024-11-16 08:25 UTC, Ixpiria approved these changes

2024-11-16 10:19 UTC, EinSev commented
Don't merge yet, have to look into smth

2024-11-16 20:02 UTC, merged