feature/JP-33-journey-edit-delete
JourneyPlanner/JourneyPlanner pull request #46
Opened 2024-04-06 15:49 UTC by EinSev

2024-04-06 18:34 UTC, Ixpiria approved these changes, later dismissed

2024-04-06 18:35 UTC, EinSev commented
Don't merge before @Mathematti improves backend

2024-04-06 18:37 UTC, Mathematti requested changes, later dismissed
I need to do some quick backend improvements

2024-04-06 21:20 UTC, stefll requested changes

2024-04-06 21:20 UTC, stefll commented on frontend/components/DashboardItem.vue
>                          aria-controls="overlay_menu">
Ich glaub es ist hier
Ich finde das Menü sollte weiterhin gezeigt werden wenn man auf löschen geht
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/b928df8a-cb11-4b5e-88df-89b2fad91338)
Aja und meldung in darkmode dunkel machen

2024-04-06 21:20 UTC, stefll commented on frontend/components/DashboardItem.vue
> + * when submitting form, fields are checked for validation
weiß nicht genau wo das ist. Aber generell weniger white space zwischen den Zeilen bitte
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/fa65d44c-85a4-456c-b103-95841c2fbec0)

2024-04-08 13:40 UTC, stefll requested changes
Design Review: A few things to be fixed

2024-04-08 13:40 UTC, stefll commented on frontend/components/DashboardItem.vue
>                      </NuxtLink>
Ich werde es mal hier hinschreiben
Wenn man eine Reise löschen will popt das Warning Pop up mehrmals überinander.
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/acacab7e-af5c-4bbc-b90e-fc6d4b60e587)
Nach dem man 2 mal auf das x geklickt hat:
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/0b8c4f3c-f9c5-4077-9f46-cd1c516490fd)

Die pop ups tauschen so oft vor wie es insgesamt Reisen gibt. (bei 6 Reisen = 6 Pop ups)

2024-04-08 13:40 UTC, stefll commented on frontend/components/DashboardItem.vue
>                      <button class="pi pi-ellipsis-v justify-end" @click="toggle" aria-haspopup="true"
bitte die Buttons gleich groß machen 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/401a467a-2c7c-4b22-8afc-36d08bc7e99f)

2024-04-08 19:26 UTC, Ixpiria approved these changes, later dismissed

2024-04-08 19:47 UTC, stefll requested changes
Design Review: A few things have to be changed

2024-04-08 19:47 UTC, stefll commented on frontend/components/form/Input.vue
> +      <span class="ml-3 text-error dark:text-error-dark dark:font-bold text-xs" :class="{
Die Textfarbe bei dem popup bitte auch auf ein anderes Rot ändern (Dark and Light)
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/e9111365-8e9e-412f-baed-e3f25297e2a7)

2024-04-08 19:47 UTC, stefll commented on frontend/components/form/Input.vue
Englische Verion 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/675618ba-2e75-4098-940a-a42a0d4eb790)

2024-04-08 21:02 UTC, stefll approved these changes
Design Review: Everything looks good!

2024-04-08 21:07 UTC, Ixpiria approved these changes

2024-04-08 21:09 UTC, merged