Feature/jp 13 create activity
JourneyPlanner/JourneyPlanner pull request #73
Opened 2024-04-23 06:41 UTC by EinSev

2024-04-23 09:43 UTC, stefll requested changes
DEsign Review: some changes

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +<script setup lang="ts">
Das x soll eine stufe größer werden und auch bitte dem Design folgen
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/cafbf26a-5559-4219-84ef-5aa78bcdbbea)

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +import * as yup from "yup";
Diesen header (also all die Tabnamen und tab bar) weiter nach oben.
Die Tabnamen eine textgröße größer
Die Tabnamen näher an diese Tabbar

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +const toast = useToast();
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/65f2bc8e-a5c3-4f0c-8298-47e3f3cdcb4b)
Die Inputs besser koordinieren also mach leiber ein gridsystem mit drei collums und die inputsfelder Name und addresse soll eben 2 collumns breit sein und die anderen input felder nur in collumn breit. Aber auf der linken seite einen margin rechts machen damit es dann doch nicht so lang wirkt

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +
Das Activity Forms Feld so zu sagen das ganze soll bei allen Tabs die SELBE breite und höhe haben
Das Activity Forms soll auch bei allen eine etwas kleinere länge haben.
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/74bfa0d0-fe39-40ae-a938-a3c98d1ba93a)
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/a1b11d84-4986-44d2-b0a9-f6f6bdb135ef)
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/459e2c2c-3052-48fc-905f-f7cca2471685)

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +
wenn du schon placeholder machst dann bitte überall 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/50d7679e-877c-4e84-b27c-528f20e3d83c)

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +const selectedDate = ref();
Error mesage bitte unter startzeit oder so

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +watch(
Es werden immer zuerst Österreichische standorte angezeigt 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/b5c8ed68-c285-4b49-8820-705ba5a0fcfe)

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +    },
Nachdem eine Aktivität abgebrochen wurde soll man beim erstellen einer neuen Aktivität wieder bei dem ersten Tab landen
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/ea9ff438-603d-4520-af51-9e6ab6d391fc)

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +    name: string;
Ich weiß nicht wieso aber nachdem ich das datum der reise geändert habe wird die zeitspanne im Creation calander nicht mehr fett angezeigt 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/3c65e742-ce74-4279-8413-cde7f99f2491)

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +    description: string;
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/1882d79b-199a-43b0-bce6-f69b810bc425)

Die Input titel eine schriftgröße größer oder/und error message kleiner (ich weiß grad nicht ob die überall gleich ist

2024-04-23 09:43 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +    phone: string;
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/55e1d49a-e666-4757-9c0e-b60527594da9)
Die Felder etwas zusammenrücken

2024-04-23 11:23 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +import * as yup from "yup";
text size verändert, rest geht nicht wirklich

2024-04-23 12:28 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +watch(
can't fix, ist so von Mapbox

schweden schloss findet man wenn man Kungliga slottet eingibt

2024-04-23 12:31 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +    name: string;
can't reproduce

2024-04-23 12:48 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +const selectedDate = ref();
can't fix, hope its okay

2024-04-24 14:25 UTC, Mathematti submitted a review, later dismissed
deployment needs to be fixed I think, don't merge yet

2024-04-24 20:58 UTC, EinSev commented on frontend/components/ActivityDialog.vue
> +    phone: string;
cant fix fast

2024-04-24 22:05 UTC, stefll requested changes
Design Review: few changes

2024-04-24 22:05 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +                >
Mache diese Changes hier 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/2819146f-a757-45e6-886f-c3897c528318)

2024-04-24 22:05 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +        class="z-50 flex h-[80vh] w-full flex-col rounded-lg bg-background font-nunito dark:bg-background-dark sm:h-[70vh] sm:w-6/12 md:rounded-xl"
change the h to this 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/a125dc62-dcac-4d89-ad7d-eae99d380c65)

2024-04-24 22:05 UTC, stefll commented on frontend/components/ActivityDialog.vue
> +<script setup lang="ts">
Den X Button etwas größer bitte wenn es geht

2024-04-25 16:45 UTC, Ixpiria approved these changes, later dismissed

2024-04-25 19:31 UTC, EinSev commented
Waiting for backend tomorrow morning from @Mathematti

2024-04-27 15:02 UTC, Ixpiria approved these changes, later dismissed

2024-04-27 16:03 UTC, stefll approved these changes, later dismissed
Design Review: Everything looks fine

2024-04-27 19:05 UTC, Ixpiria approved these changes

2024-04-27 19:37 UTC, stefll approved these changes
Design Review: Everything is okay

2024-04-27 19:45 UTC, merged