Feature/jp 34 leave journey
JourneyPlanner/JourneyPlanner pull request #75
Opened 2024-04-25 16:38 UTC by EinSev

2024-04-25 17:03 UTC, Ixpiria approved these changes, later dismissed

2024-04-27 19:21 UTC, stefll requested changes
Design Review: Found one flaw

2024-04-27 19:21 UTC, stefll commented on frontend/pages/journey/[id].vue
>  import Toast from "primevue/toast";
Dark mode -> Kein hover mode 
![image](https://github.com/JourneyPlanner/JourneyPlanner/assets/125883002/4b1d0bf5-8d2a-4821-b686-2beb2049e1d0)

2024-04-27 19:44 UTC, Ixpiria approved these changes

2024-04-27 19:51 UTC, stefll approved these changes
Design Review: Design is okay

2024-04-27 20:50 UTC, merged